package kohgylw.kiftd.newcore.domain;

public enum ResultCode {

	SUCCESS("SUCCESS", "操作成功"),
	ERROR("ERROR", "操作失败"),
	BAD_REQUEST("BAD_REQUEST", "请求参数错误"),
	UNAUTHORIZED("UNAUTHORIZED", "未授权"),
	FORBIDDEN("FORBIDDEN", "禁止访问"),
	NOT_FOUND("NOT_FOUND", "资源不存在"),
	INTERNAL_SERVER_ERROR("INTERNAL_SERVER_ERROR", "服务器内部错误"),
	METHOD_NOT_ALLOWED("METHOD_NOT_ALLOWED", "请求方法不允许"),
	PAYLOAD_TOO_LARGE("PAYLOAD_TOO_LARGE", "请求体过大"),

	USER_NOT_FOUND("USER_NOT_FOUND", "用户不存在"),
	USER_ALREADY_EXISTS("USER_ALREADY_EXISTS", "用户已存在"),
	USERNAME_OR_PASSWORD_ERROR("USERNAME_OR_PASSWORD_ERROR", "用户名或密码错误"),
	PASSWORD_TOO_WEAK("PASSWORD_TOO_WEAK", "密码强度不足"),
	PASSWORD_CHANGE_NOT_ALLOWED("PASSWORD_CHANGE_NOT_ALLOWED", "不允许修改密码"),
	SIGN_UP_NOT_ALLOWED("SIGN_UP_NOT_ALLOWED", "不允许注册"),

	FOLDER_NOT_FOUND("FOLDER_NOT_FOUND", "文件夹不存在"),
	FOLDER_CREATE_FAILED("FOLDER_CREATE_FAILED", "创建文件夹失败"),
	FOLDER_DELETE_FAILED("FOLDER_DELETE_FAILED", "删除文件夹失败"),
	FOLDER_RENAME_FAILED("FOLDER_RENAME_FAILED", "重命名文件夹失败"),
	FOLDER_LIMIT_EXCEEDED("FOLDER_LIMIT_EXCEEDED", "文件夹数量超出限制"),
	FOLDER_ACCESS_DENIED("FOLDER_ACCESS_DENIED", "无文件夹访问权限"),

	FILE_NOT_FOUND("FILE_NOT_FOUND", "文件不存在"),
	FILE_UPLOAD_FAILED("FILE_UPLOAD_FAILED", "文件上传失败"),
	FILE_DELETE_FAILED("FILE_DELETE_FAILED", "文件删除失败"),
	FILE_RENAME_FAILED("FILE_RENAME_FAILED", "文件重命名失败"),
	FILE_SIZE_EXCEEDED("FILE_SIZE_EXCEEDED", "文件大小超出限制"),
	FILE_TYPE_NOT_ALLOWED("FILE_TYPE_NOT_ALLOWED", "不支持的文件类型"),
	FILE_ACCESS_DENIED("FILE_ACCESS_DENIED", "无文件访问权限"),
	FILE_DOWNLOAD_FAILED("FILE_DOWNLOAD_FAILED", "文件下载失败"),

	VERIFICATION_CODE_ERROR("VERIFICATION_CODE_ERROR", "验证码错误"),
	VERIFICATION_CODE_EXPIRED("VERIFICATION_CODE_EXPIRED", "验证码已过期"),

	MEDIA_PLAY_FAILED("MEDIA_PLAY_FAILED", "媒体播放失败"),
	MEDIA_NOT_SUPPORTED("MEDIA_NOT_SUPPORTED", "不支持的媒体格式"),

	STORAGE_SPACE_INSUFFICIENT("STORAGE_SPACE_INSUFFICIENT", "存储空间不足"),
	FILE_CHAIN_INVALID("FILE_CHAIN_INVALID", "文件链无效"),
	FILE_CHAIN_EXPIRED("FILE_CHAIN_EXPIRED", "文件链已过期");

	private final String code;
	private final String message;

	ResultCode(String code, String message) {
		this.code = code;
		this.message = message;
	}

	public String getCode() {
		return code;
	}

	public String getMessage() {
		return message;
	}
}
